name: CIINN
description: Centro de Investigacion e INovación
# Cambiar url cuando se compre el dominio y se ponga el CNAME
url: http://ciin.github.io
baseurl: #place folder name if site is served in subfolder
# permalink structure for the posts
permalink: /:title/
# amount of posts on home page, before pagination starts
paginate: 20
# permalink structure for pagination
paginate_path: /page/:num/
#The folders in which tags pages will be placed.
tag_dir: /tag
# The folders in which categories pages will be placed.
category_dir: /category
# The folders in which author pages will be placed.
author_dir: /author
# Title for the author pages (this is followed by the author name)
author_title_prefix: 'Creado por '
# The place where all of the images are stored
media_folder: /img
# default profile picture for authors where this field is not set
author_default_avatar: /profile-pic.jpg
# This is where you can place all of your social media accounts
tumblr: "#"
pinterest: "#"
instagram: "#"
twitter: "#"
facebook: "#"
youtube: "#"
vimeo: "#"
soundcloud: "#"

# default front matter stuff
encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      type: "standard"
      homedisplay: "featimg"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md, documentation]

# prose.io configurations
prose:
  media: "img"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          help: "display post at full width or with sidebar"
          options:
            - name: "with sidebar"
              value: "post"
            - name: "full width"
              value: "post_full"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          help: "author id as defined within _data/authors.yml"
          type: "text"
      - name: "featimg"
        field:
          element: "text"
          label: "Featured Image"
          help: "featured image within the img-folder"
          type: "text"
      - name: "type"
        field:
          element: "select"
          label: "Post Type"
          help: "each type has some special feature"
          options:
            - name: "Standard"
              value: "standard"
            - name: "Image"
              value: "image"
            - name: "Gallery"
              value: "gallery"
            - name: "Audio"
              value: "audio"
            - name: "YouTube"
              value: "youtube"
            - name: "Vimeo"
              value: "vimeo"
      - name: "homedisplay"
        field:
          element: "select"
          label: "Home Display"
          help: "decide whether to display embedded element (for post types: audio, youtube, vimeo) or Featured Image on home page"
          options:
            - name: "Featured Image"
              value: "featimg"
            - name: "Embedded Element"
              value: "iframe"
      - name: "vimeo-embed"
        field:
          element: "text"
          label: "Vimeo Embedding Code"
          help: "Set post type to vimeo in order for this to work"
      - name: "gallery-id"
        field:
          element: "text"
          label: "Gallery ID"
          help: "ID of the gallery defined within _data/galleries.yml - use include in content to use"
      - name: "audio-embed"
        field:
          element: "text"
          label: "Audio Embedding Code"
          help: "Set post type to audio in order for this to work"
      - name: "yt-video-id"
        field:
          element: "text"
          label: "YouTube Video ID"
          help: "Set post type to youtube in order for this to work. Do not set featured image, as the youtube video thumbnail will be used"
          type: "text"

